### ISSUE TITLE
Attempted import Error: 'IAccordionProps' is not exported from './components/Accordion/Accordion'

### ISSUE THREAD

**Issue by RobLMartin** [appnexus/lucid#1153]
Hey, I followed the README because I wanted try out lucid, but I am getting the above error when importing the Button component. I'm using lucid-ui at version ^5.8.1.

**Comment by jondlm** [comment]
Hey there! Thanks for reporting the issue. We've been living with the warning since it was introduced. It basically boils down to introducing a feature that typescript supports but babel-typescript doesn't. We need to strip some of the exports from our index file. Hopefully we'll tackle this soon.

For the moment it's just an inconvenience since the components still work but we really should fix it soon!
