### ISSUE TITLE
TextField (when isMultiLine is true) can't accept `style` prop correctly

### ISSUE THREAD

**Issue by kl2735** [appnexus/lucid#154]
the style i passed in to TextField didn't get passed to <textarea>, but to its wrapper div. that makes some style like `height` didn't take effect on this component. 

Also, when i drag to resize, the border will go over the next item on the page instead of pushing the next item.

**Comment by kl2735** [comment]
![screen shot 2016-03-30 at 3 35 17 pm](https://cloud.githubusercontent.com/assets/6750027/14158063/278f4e76-f69c-11e5-938f-133ea3a66042.png)

**Comment by jondlm** [comment]
I'd suggest using the `rows` prop to make the multi line version taller. Passing styles to the root element is actually a convention we enforce with [a common test][t] since it could differ wildly based on the component you're using.

[t]: https://github.com/appnexus/lucid/blob/master/src/util/generic-tests.jsx#L21-L28

**Comment by jondlm** [comment]
I can't reproduce the dragging issue. Could you give me some more details after you're tried `rows` instead?

**Comment by kl2735** [comment]
@jondlm   oh, maybe i was editing the html which breaks the ui. yeah, i can't produce dragging issue too now. Let us assume that that part is fine.

**Comment by kl2735** [comment]
for the height, i am ok to use row. and it makes sense to pass the style to the root elements too.
Feel free to close this issue then

**Comment by jondlm** [comment]
Sounds good!
