### ISSUE TITLE
Paginator textfield reverts back to default value on update

### ISSUE THREAD

**Issue by reddyesha** [appnexus/lucid#347]
**Reproduction Steps**
1. Click into Paginator textfield
2. Update page to `12`
3. Click away or hit enter

**Expected:** Textfield retains number entered by user.
**Actual:** Textfield reverts back to default value of `1`.

![screen shot 2016-06-14 at 3 02 54 pm](https://cloud.githubusercontent.com/assets/4751583/16061327/4003f7e6-3241-11e6-913f-89458b92c450.png)
![screen shot 2016-06-14 at 3 03 05 pm](https://cloud.githubusercontent.com/assets/4751583/16061328/40394eb4-3241-11e6-8ee3-2750b24c9a05.png)
![screen shot 2016-06-14 at 3 03 13 pm](https://cloud.githubusercontent.com/assets/4751583/16061326/40034c38-3241-11e6-88ed-f3cfd964a1a2.png)

**Comment by reddyesha** [comment]
`Paginator.handleTextFieldChange` expects `(value, totalPages)`. But instead, is receiving the following from `TextField.onSubmit`: `(value, {event, props: this.props })`.

In `Paginator.reducers.onPageSelect`, `selectedPageIndex` always gets set to `0` ->
`selectedPageIndex: _.clamp(pageIndex, 0, totalPages - 1)`, where `totalPages` is an object, not a number.

The fix was to calculate the correct value for `totalPages` in `Paginator.handleTextFieldChange` based on `totalCount` and `selectedPageSizeIndex` and pass that to `Paginator.reducers.onPageSelect`.

**Comment by sodiumjoe** [comment]
it looks like the `totalPages` that's already calculated is being partialed onto `TextField.onSubmit`: https://github.com/reddyesha/lucid/blob/9dd21202d7840265d0628cae1fdfff0cca9534aa/src/components/Paginator/Paginator.jsx#L177

**Comment by sodiumjoe** [comment]
so, this turns out to be an incorrect use of `_.partialRight`https://github.com/reddyesha/lucid/blob/9dd21202d7840265d0628cae1fdfff0cca9534aa/src/components/Paginator/Paginator.jsx#L177

That's tacking the `totalPages` onto the end of the arg list, instead of applying it as the second argument as I expected it to.

`totalPages` originates in `this.props` (it's calculated in the selector), so you can actually just grab it off of props in `handleTextFieldChange`: https://github.com/reddyesha/lucid/blob/9dd21202d7840265d0628cae1fdfff0cca9534aa/src/components/Paginator/Paginator.jsx#L123
