### ISSUE TITLE
Recommend a pattern for avoiding function creation in renders

### ISSUE THREAD

**Issue by jondlm** [appnexus/lucid#432]
It's a well known that creating closured functions in your render body can have a negative impact on performance. We need to come up with a better recommendation than the "props as last callback arg" approach we've used before. React started throwing warnings if extra props were passed through to native dom elements, which directly conflicts with our recommendation of attaching a "dummy" prop that can later be extracted at callback time.

**Comment by mute** [comment]
Refresher on the issue this is trying to address: https://ryanfunduk.com/articles/never-bind-in-render/

There are basically two situations we need to have an opinion on:

**Simple**
```javascript
var Item = React.createClass({
  render() {
    return (
        <span onClick={() => {
          this.props.doSomethingWith(this.props.someProp);
        }}>
          ...
        </span>
    );
  }
});
```

Probably should be:
```javascript
var Item = React.createClass({
  handleClick() {
    this.props.doSomethingWith(this.props.someProp);
  }

  render() {
    return (
        <span onClick={this.handleClick}>
          ...
        </span>
    );
  }
});
```

**Binding Arguments / Partial Functions**
This case is outlined well here, so I won't repeat it: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md#protips

The gist of the suggested solution is that, in the case where a function is being created as a `partial`, it should really be an indicator that it's a place where a smaller Component should be used instead.

Here's a real example where this solution isn't ideal that's worth considering:
```javascript
export default React.createClass({
  getInitialState() {
    return {
      currentList: 'one',
      selectedIndices: [0],
    };
  },

  handleSelect(currentList, index) {
    this.setState({
      currentList,
      selectedIndices: [index],
    });
  },

  render() {
    return (
      <VerticalListMenu
        onSelect={_.partial(this.handleSelect, 'one')}
        selectedIndices={this.state.currentList === 'one' ? this.state.selectedIndices : []}
      >
        ...
      </VerticalListMenu>
    );
  },
});
```

For this use case, a user would need to make a very limited use component to wrap `VerticalListMenu`, e.g.:

```javascript
export default React.createClass({
  handleSelect() {
    this.props.onSelect(this.props.identifier);
  },

  render() {
    return (
      <VerticalListMenu
        onSelect={this.handleSelect}
        {_.omit(...this.props, ['onSelect', 'identifier']))}
      >
      </VerticalListMenu>
    );
  },
});
```

Having tiny components is the idiomatically correct way with React, but in practice, having to create these all over the place could get really cumbersome.

With that said, it seems preferable to declaring inline partial functions because it comes with rendering performance gains and should also increase testability.

**Comment by jondlm** [comment]
That's an awesome breakdown! Sounds like we should steer our consumers toward the idiomatic approach rather than trying to be clever with something like memoized partials.

**Comment by sodiumjoe** [comment]
i agree component composition is most straightforward if tedious 👍
