### ISSUE TITLE
getFirst current usage can result in multiple instances

### ISSUE THREAD

**Issue by jhsu** [appnexus/lucid#879]
```
getFirst(props, types, defaultValue)
```
usually requires something like: 
```
const paginator = getFirst(this.props, DataTablePanel.Paginator, <DataTablePanel.Paginator {...Paginator}/>);
```
which, when Paginator prop is used, constructs two instances of Paginator, one from `findTypes` (called by `getFirst`) and the one used for the defaultValue passed into `getFirst`.

should we be using the third argument rather than doing something like:

```
const paginator = getFirst(this.props, DataTablePanel.Paginator) || <DataTablePanel.Paginator {...Paginator}/>;
```
so that only one element is ever created?

**Comment by ogupte** [comment]
yes this seems like a good way to improve performance. In most cases, elements created are really minimal component wrappers with `render: () => null` so creating elements from these components normally don't cause performance issues, but since it's not always the case, using more short-circuit evaluation like you suggest can only make things better.
